camera:
  rtsp_url: "YOUR_RTSP_URL_HERE"

thresholds:
  bark: 0.70
  dog: 0.70

settings:
  bark_release_seconds: 5
  model: "models/yamnet.tflite"

mqtt:
  broker: "core-mosquitto"
  port: 1883
  username: "dog_bark_detector"
  password: "DogBark1234!"

device:
  name: "Dog Bark Detector"
  manufacturer: "Luca Lunetti"
  model: "RTSP Bark Detector"
  version: "0.1"
